pipeline {
   tools {
        maven 'Maven3'
    }
    agent any
    environment {
        registry = "858903924214.dkr.ecr.us-east-1.amazonaws.com/eks-demo-app"
    }
   
    stages {
        stage('Cloning Git') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '', url: 'https://github.com/akannan1087/docker-spring-boot']]])     
            }
        }
      stage ('Build') {
          steps {
            sh 'mvn clean install'           
            }
      }
    // Building Docker images
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry 
          dockerImage.tag("$BUILD_NUMBER")
        }
      }
    }
    // Uploading Docker images into AWS ECR
    stage('Pushing to ECR') {
     steps{  
        withAWS(region: 'us-east-1', credentials: 'awsaccess') {
         script {
                sh 'aws ecr get-login-password --region ${env.awsRegion} | docker login --username AWS --password-stdin ${env.registry}'
                sh 'docker push 858903924214.dkr.ecr.us-east-1.amazonaws.com/eks-demo-app:$BUILD_NUMBER'
         }
        }
     }
      }
        stage ('Helm Deploy') {
          steps {
            script {
                sh "helm upgrade first --install .sample-app/mychart --namespace demo-app --set image.tag=$BUILD_NUMBER"
                }
            }
        }
    }
}